Update build-dotnet-core.yml "Determine Test Project"

diff --git a/.github/workflows/build-dotnet-core.yml b/.github/workflows/build-dotnet-core.yml
--- a/.github/workflows/build-dotnet-core.yml
+++ b/.github/workflows/build-dotnet-core.yml
@@ -68,31 +68,31 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Determine Test Project
-        id: set-project
+      - name: Determine Test Project (if Windows)
+        if: runner.os == 'Windows'
         run: |
-          if [[ "$RUNNER_OS" == "Windows" ]]; then
-            if (${{ matrix.dotnet }} -eq "2.1.x") { Write-Output "project=Collections.Extensions.ToPyString.NetCore21.Tests" } 
-            elseif (${{ matrix.dotnet }} -eq "3.1.x") { Write-Output "project=Collections.Extensions.ToPyString.NetCore31.Tests" } 
-            elseif (${{ matrix.dotnet }} -eq "5.0.x") { Write-Output "project=Collections.Extensions.ToPyString.Net50.Tests" } 
-            elseif (${{ matrix.dotnet }} -eq "6.0.x") { Write-Output "project=Collections.Extensions.ToPyString.Net60.Tests" } 
-            elseif (${{ matrix.dotnet }} -eq "7.0.x") { Write-Output "project=Collections.Extensions.ToPyString.Net70.Tests" } 
-            elseif (${{ matrix.dotnet }} -eq "8.0.x") { Write-Output "project=Collections.Extensions.ToPyString.Net80.Tests" } 
-            elseif (${{ matrix.dotnet }} -eq "9.0.x") { Write-Output "project=Collections.Extensions.ToPyString.Net90.Tests" } 
-            else { Write-Error "Unsupported .NET version: ${{ matrix.dotnet }}" }
-          else
-            # Code for Linux/macOS
-            case "${{ matrix.dotnet }}" in
-              "2.1.x") echo "project=Collections.Extensions.ToPyString.NetCore21.Tests" ;;
-              "3.1.x") echo "project=Collections.Extensions.ToPyString.NetCore31.Tests" ;;
-              "5.0.x") echo "project=Collections.Extensions.ToPyString.Net50.Tests" ;;
-              "6.0.x") echo "project=Collections.Extensions.ToPyString.Net60.Tests" ;;
-              "7.0.x") echo "project=Collections.Extensions.ToPyString.Net70.Tests" ;;
-              "8.0.x") echo "project=Collections.Extensions.ToPyString.Net80.Tests" ;;
-              "9.0.x") echo "project=Collections.Extensions.ToPyString.Net90.Tests" ;;
-              *) echo "Error: Unsupported .NET version: ${{ matrix.dotnet }}" && exit 1 ;;
-            esac
-          fi
+          if (${{ matrix.dotnet }} -eq "2.1.x") { echo "PROJECT=Collections.Extensions.ToPyString.NetCore21.Tests" >> $env:GITHUB_ENV }
+          elseif (${{ matrix.dotnet }} -eq "3.1.x") { echo "PROJECT=Collections.Extensions.ToPyString.NetCore31.Tests" >> $env:GITHUB_ENV }
+          elseif (${{ matrix.dotnet }} -eq "5.0.x") { echo "PROJECT=Collections.Extensions.ToPyString.Net50.Tests" >> $env:GITHUB_ENV }
+          elseif (${{ matrix.dotnet }} -eq "6.0.x") { echo "PROJECT=Collections.Extensions.ToPyString.Net60.Tests" >> $env:GITHUB_ENV }
+          elseif (${{ matrix.dotnet }} -eq "7.0.x") { echo "PROJECT=Collections.Extensions.ToPyString.Net70.Tests" >> $env:GITHUB_ENV }
+          elseif (${{ matrix.dotnet }} -eq "8.0.x") { echo "PROJECT=Collections.Extensions.ToPyString.Net80.Tests" >> $env:GITHUB_ENV }
+          elseif (${{ matrix.dotnet }} -eq "9.0.x") { echo "PROJECT=Collections.Extensions.ToPyString.Net90.Tests" >> $env:GITHUB_ENV }
+          else { Write-Error "Unsupported .NET version: ${{ matrix.dotnet }}" }
+      
+      - name: Determine Test Project (if UNIX)
+        if: runner.os == 'macOS' || runner.os == 'Linux'
+        run: |
+          case "${{ matrix.dotnet }}" in
+            "2.1.x") echo "PROJECT=Collections.Extensions.ToPyString.NetCore21.Tests" >> "$GITHUB_ENV" ;;
+            "3.1.x") echo "PROJECT=Collections.Extensions.ToPyString.NetCore31.Tests" >> "$GITHUB_ENV" ;;
+            "5.0.x") echo "PROJECT=Collections.Extensions.ToPyString.Net50.Tests" >> "$GITHUB_ENV" ;;
+            "6.0.x") echo "PROJECT=Collections.Extensions.ToPyString.Net60.Tests" >> "$GITHUB_ENV" ;;
+            "7.0.x") echo "PROJECT=Collections.Extensions.ToPyString.Net70.Tests" >> "$GITHUB_ENV" ;;
+            "8.0.x") echo "PROJECT=Collections.Extensions.ToPyString.Net80.Tests" >> "$GITHUB_ENV" ;;
+            "9.0.x") echo "PROJECT=Collections.Extensions.ToPyString.Net90.Tests" >> "$GITHUB_ENV" ;;
+            *) echo "Error: Unsupported .NET version: ${{ matrix.dotnet }}" && exit 1 ;;
+          esac
 
       - name: Setup .NET
         uses: actions/setup-dotnet@v4
@@ -100,10 +100,10 @@ jobs:
           dotnet-version: ${{ matrix.dotnet }}
 
       - name: Install Dependencies
-        run: dotnet restore ${{ steps.set-project.outputs.project }}
+        run: dotnet restore ${{ env.PROJECT }}
       
       - name: Build Library
-        run: dotnet build ${{ steps.set-project.outputs.project }} --configuration Release --no-restore
+        run: dotnet build ${{ env.PROJECT }} --configuration Release --no-restore
       
       - name: Run Tests
-        run: dotnet test ${{ steps.set-project.outputs.project }} --no-restore --verbosity normal
+        run: dotnet test ${{ env.PROJECT }} --no-restore --verbosity normal
